// interface IConstants {
//   RESULTS_PER_PAGE: number;
//   RESULTS_MAX_PAGES: number;
// }

const Constants = {
  RESULTS_PER_PAGE: 5,
  RESULTS_MAX_PAGES: 3,
  FILTER_KEYS: [
    'ebook_access',
    'first_publish_year',
    'language',
    'publisher',
    'ratings_average',
    'subject',
  ],
  FILTER_KEY_VALUE_WHEN_ABSENT_FROM_DOC: 'unknown',
  SUBJECTS: [
    'Architecture',
    'Art Instruction',
    'Art History',
    'Dance',
    'Design',
    'Fashion',
    'Film',
    'Graphic Design',
    'Music',
    'Music Theory',
    'Painting',
    'Photography',
    'Bears',
    'Cats',
    'Kittens',
    'Dogs',
    'Puppies',
    'Fantasy',
    'Historical Fiction',
    'Horror',
    'Humor',
    'Literature',
    'Magic',
    'Mystery and detective stories',
    'Plays',
    'Poetry',
    'Romance',
    'Science Fiction',
    'Short Stories',
    'Thriller',
    'Young Adult',
    'Biology',
    'Chemistry',
    'Mathematics',
    'Physics',
    'Programming',
    'Management',
    'Entrepreneurship',
    'Business Economics',
    'Business Success',
    'Finance',
    'Kids Books',
    'Stories in Rhyme',
    'Baby Books',
    'Bedtime Books',
    'Picture Books',
    'Ancient Civilization',
    'Archaeology',
    'Anthropology',
    'World War II',
    'Social Life and Customs',
    'Cooking',
    'Cookbooks',
    'Mental Health',
    'Exercise',
    'Nutrition',
    'Self-help',
    'Autobiographies',
    'History',
    'Politics and Government',
    'World War II',
    'Women',
    'Kings and Rulers',
    'Composers',
    'Artists',
    'Anthropology',
    'Religion',
    'Political Science',
    'Psychology',
    'Brazil',
    'India',
    'Indonesia',
    'United States',
    'History',
    'Mathematics',
    'Geography',
    'Psychology',
    'Algebra',
    'Education',
    'Business & Economics',
    'Science',
    'Chemistry',
    'English Language',
    'Physics',
    'Computer Science',
    'English',
    'French',
    'Spanish',
    'German',
    'Russian',
    'Italian',
    'Chinese',
    'Japanese',
  ],
};

export default Constants;
